#!/usr/bin/env python3
#
# Lists the status of multiple git repositories
# Handles the repos in parallel

import argparse
import os
import re
import subprocess
import sys

from multiprocessing import Pool
from tqdm import tqdm


class Config:
    main_branches = ('master', 'staging', 'master-staging', 'community')


class Color:
    green = '\33[32m'
    grey = '\33[90m'
    red = '\33[31m'
    blue = '\33[34m'
    yellow = '\33[33m'
    end = '\33[0m'


class Flag:
    ok = '☑️'
    behind = '🐌'
    ahead = '🐇'
    new = '🆕'
    modified = '👀'
    local = '📍'
    unknown = '⁉️'


_program_name = os.path.basename(sys.argv[0])
_completions = []


def complete_argument(func):
    """Decorates command-line argument parser with fish autocomplete commands"""
    def wrapper(*args, **kwargs):
        completion = f'complete -c {_program_name} --no-files'
        for opt in args:
            if opt.startswith('-'):
                if not opt.startswith('--'):
                    completion += f' --short-option {opt[1]}'
                else:
                    completion += f' --long-option {opt[2:]}'
        description = kwargs['help']
        completion += f' --description "{description}"'
        _completions.append(completion)

        return func(*args, **kwargs)
    return wrapper


parser = argparse.ArgumentParser(
    formatter_class=argparse.RawDescriptionHelpFormatter,
    description='List the status of git repositories.',
    epilog='''status indicators:
    ☑️  : local repository is up to date with origin
    🐌 : local is behind origin
    🐇 : local is ahead of origin
    🆕 : repository has new files
    👀 : repository has modified files
    📍 : only local repository, no remote
    ⁉️  : status unknown
    '''
)
add_argument = complete_argument(parser.add_argument)

add_argument('-d', '--debug', action='store_true',
             help="print 'git status' output")
add_argument('-f', '--fetch', action='store_true',
             help="do a 'git fetch' before status")
add_argument('-p', '--pull', action='store_true',
             help="pull branches behind origin instead of showing the status")
add_argument('--completion', action='store_true',
             help="output fish shell completion commands")

args = parser.parse_args()

if args.completion:
    print('\n'.join(_completions))
    exit()


def repo_status(path):
    fetch_cmd = 'git fetch ;' if args.fetch else ''
    cmd = f'cd {path} ; {fetch_cmd} git status --'

    out = subprocess.getoutput(cmd)
    if args.debug:
        print(out)

    branch = re.search(r'On branch (\S+)', out).group(1)

    try:
        status = re.search(r'Your branch is (.*)', out).group(1)
    except AttributeError:
        status = ''  # no commits done yet

    status_flag = Flag.unknown  # unknown
    if status == '':
        status_flag = Flag.local
    elif status.startswith('up to date'):
        status_flag = Flag.ok
    elif status.startswith('behind'):
        status_flag = Flag.behind
    elif status.startswith('ahead'):
        status_flag = Flag.ahead

    new_files = Flag.new if re.search(
        r'Untracked files:|new file:', out) else ''
    modified = Flag.modified if re.search(r'modified:', out) else ''

    if new_files is not '' or modified is not '':
        color = Color.yellow
    elif status_flag == Flag.unknown:
        color = Color.red
    elif status_flag is not Flag.ok:
        color = Color.blue
    elif branch in Config.main_branches:
        color = Color.green
    else:
        color = ''

    return {
        'repo': os.path.basename(path),
        'branch': branch,
        'path': path,
        'color': color,
        'status': status_flag,
        'new': new_files,
        'modified': modified,
        'reset': Color.end
    }


def pull_repo(repo):
    out = f'{Color.green}Pulling {repo["repo"]}...{Color.end}\n'
    cmd = 'cd {path} ; git pull'.format(**repo)
    out += subprocess.getoutput(cmd)
    out += '\n'

    if args.debug:
        print(cmd)

    print(out)


git_dirs = subprocess.getoutput(
    'find . -type d -name .git -maxdepth 4').split('\n')
repos = [os.path.dirname(d) for d in git_dirs]

with Pool(15) as p:
    status_list = list(tqdm(p.imap_unordered(
        repo_status, repos), total=len(repos)))

if args.pull:
    with Pool(5) as p:
        p.map(pull_repo, [
              r for r in status_list if r['status'] == Flag.behind])
else:
    for s in sorted(status_list, key=lambda k: k['repo']):
        print('{color}{repo} {status} {new}{modified} {branch}{reset}'.format(**s))
